.Dd 2022-06-20
.Dt MGL_GAME_INIT 3 PRM
.Os GNU/Linux
.Sh NAME
.Nm mgl_game_init
.Nd initialize mgl_game
.Sh SYNOPSIS
.In mangala.h
.Ft void
.Fn mgl_game_init "struct mgl_game *game"
.Sh DESCRIPTION
The
.Nm
function initializes the given
.Va game
structure. It fills the
.Va game->board
array with 4 except last entries in users inventory.
.Sh SEE ALSO
.Xr mgl_turn_start 3 ,
.Sh AUTHORS
.An kurth4cker Aq Mt kurth4cker@tutanota.com
